name: CI - build artifacts

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        working-directory: ./hangman-api
        run: |
          npm ci
          npm run build --if-present
      - name: Upload Artifact (dependencies)
        uses: actions/upload-artifact@v4
        with:
          name: dependencies
          path: hangman-api/node_modules/
          include-hidden-files: true

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Artifact (dependencies)
        uses: actions/download-artifact@v4
        with:
          name: dependencies
          path: hangman-api/node_modules/
      - name: Test
        working-directory: ./hangman-api
        run: |
          chmod -R +x node_modules
          npm test
