name: Test get commodity price custom action

on:
  workflow_dispatch:

jobs:
  get_commodity_price:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        commodity: ["gold", "SILVER", "wood"]
        currency: ["USD", "eur", "EURO"]

    steps:
      - name: Get commodity price
        uses: jtrillo/get-commodity-price-action@v1.0.0
        with:
          commodity: ${{ matrix.commodity }}
          currency: ${{ matrix.currency }}
